version: '3.8'

services:
  registry-api:
    container_name: pluggedin-registry-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3001}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/mcp-registry}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL:-http://elasticsearch:9200}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
    depends_on:
      - mongodb
      - elasticsearch
      - redis
    networks:
      - registry-network

  mongodb:
    container_name: pluggedin-registry-mongodb
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-mcp-registry}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - registry-network

  elasticsearch:
    container_name: pluggedin-registry-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=${ES_JAVA_OPTS:--Xms512m -Xmx512m}
      - cluster.name=${CLUSTER_NAME:-mcp-registry-cluster}
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - registry-network

  redis:
    container_name: pluggedin-registry-redis
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - registry-network

  kibana:
    container_name: pluggedin-registry-kibana
    image: docker.elastic.co/kibana/kibana:8.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - registry-network

volumes:
  mongodb_data:
    driver: local
  elasticsearch_data:
    driver: local
  redis_data:
    driver: local

networks:
  registry-network:
    driver: bridge